name: lodestar-artifacts
development: true
#if using quay then you should specify the image location
buildImage: true

servicePort: 8080

imageName: "lodestar-artifacts"
imageTag: "latest"

builderImage: registry.access.redhat.com/ubi8/openjdk-11
builderImageTag: 1.3

git:
  uri: https://github.com/rht-labs/lodestar-artifacts.git
  ref: master

db:
  mongodbServiceName: lodestar-artifacts-mongodb
  mongodbUser: mongouser
  mongodbPassword: mongopassword
  mongodbDatabase: artifacts
  mongodbAdminPassword: mongoadminpassword

api:
  gitlab: http://gitlab.com
  engagement: http://lodestar-git-api:8080

tokens:
  gitlab: nope

config:
  gitlabGroupId: 0
